# Generated by Django 5.2.9 on 2025-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('duration_ms', models.FloatField()),
                ('sql_count', models.IntegerField()),
                ('sql_data', models.JSONField()),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
