# Generated by Django 5.2.9 on 2025-12-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_monitoringlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoringlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Monitoring Log', 'verbose_name_plural': 'Monitoring Logs'},
        ),
    ]
