# Generated by Django 5.2.9 on 2025-12-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_monitoringlog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitoringLog',
        ),
    ]
