# Generated by Django 5.2.9 on 2025-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_verifycode_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
